version: "3.9"

services:
  may:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: may
    environment:
      - API_ID=${APP_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - OWNER=${OWNER}
      - FFMPEG=${FFMPEG}
    volumes:
      - "/codebase:/codebase"
      - "/storage:/storage"
    restart: always
